# Generated by Django 5.2.11 on 2026-03-31 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mfa", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mfamethod",
            name="_backup_codes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON field storing backup codes for account recovery",
                verbose_name="backup codes",
            ),
        ),
        migrations.AlterField(
            model_name="mfamethod",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether this method is active and can be used",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="mfamethod",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the user's primary MFA method",
                verbose_name="is primary",
            ),
        ),
        migrations.AlterField(
            model_name="mfamethod",
            name="name",
            field=models.CharField(
                help_text="MFA method name (e.g., 'app', 'email')",
                max_length=255,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="mfamethod",
            name="secret",
            field=models.CharField(
                help_text="TOTP secret key for generating verification codes",
                max_length=255,
                verbose_name="secret",
            ),
        ),
        migrations.AlterField(
            model_name="mfamethod",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this MFA method",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mfa_methods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
